import Head from "next/head";

export const LoginHead = () => (
  <Head>
    <title>Login | Columbia University</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export const HomeHead = () => (
  <Head>
    <title>Columbia University</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export const ClosureDateHead = () => (
  <Head>
    <title>Closure Date | Columbia University</title>
    <meta name="description" content="Closure Date | Columbia University" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export const UsersHead = () => (
  <Head>
    <title>Users | Columbia University</title>
    <meta name="description" content="Users | Columbia University" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export const DepartmentsHead = () => (
  <Head>
    <title>Departments | Columbia University</title>
    <meta name="description" content="Departments | Columbia University" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export const CategoriesHead = () => (
  <Head>
    <title>Categories | Columbia University</title>
    <meta name="description" content="Departments | Columbia University" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export const ReportsHead = () => (
  <Head>
    <title>Reports | Columbia University</title>
    <meta name="description" content="Reports | Columbia University" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);
